version: '1.0'

services:
  web:
    depends_on:
      - db
    build: .
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=videos
      - SSLMode=disable
      - DB_PASSWORD=123qwe
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    restart: always
    hostname: localhost
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=videos
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./schema/db.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-db:
      